### ISSUE TITLE
OneDWaveEquation can't deal with the (k, l)=(0, 0) component of solution

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/OscillatoryFlows.jl#2]
I think one needs to be a bit careful. I'm wondering whether FourierFlows.jl handles functions with non-zero mean. Notice the animation of the [two gaussians](https://fourierflows.github.io/OscillatoryFlows.jl/dev/generated/two_gaussians/): for t>0 you see that most of the amplitude away from the gaussian is not at ξ=0 but slightly below zero. I think this has something to do with inverting from Fourier space...

Or it may be related to this line
https://github.com/FourierFlows/OscillatoryFlows.jl/blob/08f05b24d6f50014374cccd981646a1e9c7326a9/src/OneDWaveEquation.jl#L126
Why is this line there?

**Comment by navidcy** [comment]
OK, I see... that line is there because σ(c, k=0) = 0 and then `ξh` has NaNs as first element...

**Comment by navidcy** [comment]
There are integral properties of the wave equation that relate the 0-th mode (mean of ξ and mean of u) with the integral properties of the initial conditions. We should enforce them; otherwise it's wrong.

Let's denote Ξ = ∫ ξ dx, U = ∫ u dx.  From the wave equation
ξ_tt - c² ξ_xx = - β ξ_t
we immediately see that after integrating over the whole domain we have
𝝏_t U = -β U ==> U(t) =e^(-βt) U(0)

Also
𝝏_t Ξ = e^(-βt) U(0) ==> Ξ(t) = Ξ(0) + U(0)*(1-e^(-βt))/β

ξh[k=0] and uh[k=0] are directly related with Ξ and U.

**Comment by glwagner** [comment]
Ah yes! So we need to solve a different system for the k=0 mode then?

**Comment by glwagner** [comment]
Then we can directly set the mean displacement and velocity variables in `updatevars`.

**Comment by glwagner** [comment]
I think that system is already solved correctly for `U`. It's just the displacement that is tricky here.

I think we would also have to change these lines:

https://github.com/FourierFlows/OscillatoryFlows.jl/blob/08f05b24d6f50014374cccd981646a1e9c7326a9/src/OneDWaveEquation.jl#L175

**Comment by navidcy** [comment]
No need to solve different system. Simply rewrite the Ξ(t) and U(t) I've written above in terms of `ξh[0]` and `uh[0]` and then impose the solutions to the 0-th wavenumber. Note that for β->0 we have that [1-e^(-βt)]/β->t. (I can deal with it tomorrow.)

**Comment by navidcy** [comment]
ξh[0](t) = \int ξ(x, t) dx * nx/Lx = Ξ(t) nx/Lx
uh[0](t) = \int u(x, t) dx * nx/Lx = U(t) nx/Lx

Therefore, at each time-step we should set 
ξh[0](t) = ( Ξ(0) + U(0)*(1-e^(-βt))/β )  nx/Lx
uh[0](t) = ( e^(-βt) U(0) )  nx/Lx

Or actually, I don't think we need to do it every time-step. Just whenever `updatevars!` is called...

**Comment by navidcy** [comment]
(I think these solutions have name...)
